name: weather_app
description: Basic weather app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  json_annotation: ^4.0.1
  flutter_svg: ^0.21.0-nullsafety.0
  intl: ^0.17.0
  equatable: ^2.0.0
  device_preview: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.0.3
  json_serializable: ^4.1.1
  mocktail: ^0.1.2
  bloc_test: ^8.0.0

flutter:
  uses-material-design: true

